server:
  port: 20006

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/doc?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: gzw941120
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000

logging:
  level:
    db.cl.gao: debug