server:
  port: 20006

#默认数据库。随便给一个就行
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/doc?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: gzw941120
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000


mybatis:
  # Mapper XML文件位置
  mapper-locations: classpath:mapper/*.xml
  # 实体类包名
  type-aliases-package: db.cl.gao.common.model
  configuration:
    # 开启驼峰命名转换
    map-underscore-to-camel-case: true
    # 开启缓存
    cache-enabled: true
    # 开启延迟加载
    lazy-loading-enabled: true
    # 日志实现
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# PageHelper配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

spring.jackson.date-format: yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone: GMT+8


# 验证码配置
captcha:
  border: yes
  border-color: 105,179,90
  image-width: 160
  image-height: 60
  text-producer-font-size: 38
  text-producer-char-length: 4
  text-producer-char-space: 3

# JWT配置
jwt:
  secret:
    base: "gao_yw_wh_009412sq"
    refresh-interval: 43200000  # 12小时刷新一次
  expiration: 86400000  # 24小时
  header: Authorization
  token-prefix: "Bearer "



#系统默认账户、密码
system:
  account: admin
  password: 122800

logging:
  level:
    db.cl.gao: info