server:
  port: 20006

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/doc?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: gzw941120
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000


mybatis:
  # Mapper XML文件位置
  mapper-locations: classpath:mapper/*.xml
  # 实体类包名
  type-aliases-package: db.cl.gao.common.model
  configuration:
    # 开启驼峰命名转换
    map-underscore-to-camel-case: true
    # 开启缓存
    cache-enabled: true
    # 开启延迟加载
    lazy-loading-enabled: true
    # 日志实现
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# PageHelper配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

spring.jackson.date-format: yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone: GMT+8

logging:
  level:
    db.cl.gao: info